project_id = "gnclzxgemzairuwytzcl"

[functions.chat]
verify_jwt = false

[functions.youtube-search]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.generate-worksheet]
verify_jwt = false
