/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVideoGeneratorRouteImport } from './routes/_app.video-generator'
import { Route as AppTeacherRouteImport } from './routes/_app.teacher'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppJournalRouteImport } from './routes/_app.journal'
import { Route as AppImageGeneratorRouteImport } from './routes/_app.image-generator'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClassesRouteImport } from './routes/_app.classes'
import { Route as AppChatbotRouteImport } from './routes/_app.chatbot'
import { Route as AppAssignmentsRouteImport } from './routes/_app.assignments'
import { Route as AppAboutRouteImport } from './routes/_app.about'
import { Route as AppGamesIndexRouteImport } from './routes/_app.games.index'
import { Route as AppTeacherWorksheetsRouteImport } from './routes/_app.teacher.worksheets'
import { Route as AppTeacherQuizzesRouteImport } from './routes/_app.teacher.quizzes'
import { Route as AppTeacherClassesRouteImport } from './routes/_app.teacher.classes'
import { Route as AppTeacherAssignmentsRouteImport } from './routes/_app.teacher.assignments'
import { Route as AppGamesTermMatchRouteImport } from './routes/_app.games.term-match'
import { Route as AppGamesMapQuizRouteImport } from './routes/_app.games.map-quiz'
import { Route as AppGamesGameIdRouteImport } from './routes/_app.games.$gameId'
import { Route as AppAssignmentsIdRouteImport } from './routes/_app.assignments.$id'
import { Route as AppTeacherWorksheetsIdRouteImport } from './routes/_app.teacher.worksheets.$id'
import { Route as AppTeacherQuizzesIdRouteImport } from './routes/_app.teacher.quizzes.$id'
import { Route as AppTeacherGradebookAssignmentIdRouteImport } from './routes/_app.teacher.gradebook.$assignmentId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVideoGeneratorRoute = AppVideoGeneratorRouteImport.update({
  id: '/video-generator',
  path: '/video-generator',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherRoute = AppTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppImageGeneratorRoute = AppImageGeneratorRouteImport.update({
  id: '/image-generator',
  path: '/image-generator',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppChatbotRoute = AppChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesIndexRoute = AppGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherWorksheetsRoute = AppTeacherWorksheetsRouteImport.update({
  id: '/worksheets',
  path: '/worksheets',
  getParentRoute: () => AppTeacherRoute,
} as any)
const AppTeacherQuizzesRoute = AppTeacherQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AppTeacherRoute,
} as any)
const AppTeacherClassesRoute = AppTeacherClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppTeacherRoute,
} as any)
const AppTeacherAssignmentsRoute = AppTeacherAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppTeacherRoute,
} as any)
const AppGamesTermMatchRoute = AppGamesTermMatchRouteImport.update({
  id: '/games/term-match',
  path: '/games/term-match',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesMapQuizRoute = AppGamesMapQuizRouteImport.update({
  id: '/games/map-quiz',
  path: '/games/map-quiz',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesGameIdRoute = AppGamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsIdRoute = AppAssignmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAssignmentsRoute,
} as any)
const AppTeacherWorksheetsIdRoute = AppTeacherWorksheetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTeacherWorksheetsRoute,
} as any)
const AppTeacherQuizzesIdRoute = AppTeacherQuizzesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTeacherQuizzesRoute,
} as any)
const AppTeacherGradebookAssignmentIdRoute =
  AppTeacherGradebookAssignmentIdRouteImport.update({
    id: '/gradebook/$assignmentId',
    path: '/gradebook/$assignmentId',
    getParentRoute: () => AppTeacherRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof AppAboutRoute
  '/assignments': typeof AppAssignmentsRouteWithChildren
  '/chatbot': typeof AppChatbotRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/image-generator': typeof AppImageGeneratorRoute
  '/journal': typeof AppJournalRoute
  '/profile': typeof AppProfileRoute
  '/teacher': typeof AppTeacherRouteWithChildren
  '/video-generator': typeof AppVideoGeneratorRoute
  '/assignments/$id': typeof AppAssignmentsIdRoute
  '/games/$gameId': typeof AppGamesGameIdRoute
  '/games/map-quiz': typeof AppGamesMapQuizRoute
  '/games/term-match': typeof AppGamesTermMatchRoute
  '/teacher/assignments': typeof AppTeacherAssignmentsRoute
  '/teacher/classes': typeof AppTeacherClassesRoute
  '/teacher/quizzes': typeof AppTeacherQuizzesRouteWithChildren
  '/teacher/worksheets': typeof AppTeacherWorksheetsRouteWithChildren
  '/games/': typeof AppGamesIndexRoute
  '/teacher/gradebook/$assignmentId': typeof AppTeacherGradebookAssignmentIdRoute
  '/teacher/quizzes/$id': typeof AppTeacherQuizzesIdRoute
  '/teacher/worksheets/$id': typeof AppTeacherWorksheetsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof AppAboutRoute
  '/assignments': typeof AppAssignmentsRouteWithChildren
  '/chatbot': typeof AppChatbotRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/image-generator': typeof AppImageGeneratorRoute
  '/journal': typeof AppJournalRoute
  '/profile': typeof AppProfileRoute
  '/teacher': typeof AppTeacherRouteWithChildren
  '/video-generator': typeof AppVideoGeneratorRoute
  '/assignments/$id': typeof AppAssignmentsIdRoute
  '/games/$gameId': typeof AppGamesGameIdRoute
  '/games/map-quiz': typeof AppGamesMapQuizRoute
  '/games/term-match': typeof AppGamesTermMatchRoute
  '/teacher/assignments': typeof AppTeacherAssignmentsRoute
  '/teacher/classes': typeof AppTeacherClassesRoute
  '/teacher/quizzes': typeof AppTeacherQuizzesRouteWithChildren
  '/teacher/worksheets': typeof AppTeacherWorksheetsRouteWithChildren
  '/games': typeof AppGamesIndexRoute
  '/teacher/gradebook/$assignmentId': typeof AppTeacherGradebookAssignmentIdRoute
  '/teacher/quizzes/$id': typeof AppTeacherQuizzesIdRoute
  '/teacher/worksheets/$id': typeof AppTeacherWorksheetsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/assignments': typeof AppAssignmentsRouteWithChildren
  '/_app/chatbot': typeof AppChatbotRoute
  '/_app/classes': typeof AppClassesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/image-generator': typeof AppImageGeneratorRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/teacher': typeof AppTeacherRouteWithChildren
  '/_app/video-generator': typeof AppVideoGeneratorRoute
  '/_app/assignments/$id': typeof AppAssignmentsIdRoute
  '/_app/games/$gameId': typeof AppGamesGameIdRoute
  '/_app/games/map-quiz': typeof AppGamesMapQuizRoute
  '/_app/games/term-match': typeof AppGamesTermMatchRoute
  '/_app/teacher/assignments': typeof AppTeacherAssignmentsRoute
  '/_app/teacher/classes': typeof AppTeacherClassesRoute
  '/_app/teacher/quizzes': typeof AppTeacherQuizzesRouteWithChildren
  '/_app/teacher/worksheets': typeof AppTeacherWorksheetsRouteWithChildren
  '/_app/games/': typeof AppGamesIndexRoute
  '/_app/teacher/gradebook/$assignmentId': typeof AppTeacherGradebookAssignmentIdRoute
  '/_app/teacher/quizzes/$id': typeof AppTeacherQuizzesIdRoute
  '/_app/teacher/worksheets/$id': typeof AppTeacherWorksheetsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/about'
    | '/assignments'
    | '/chatbot'
    | '/classes'
    | '/dashboard'
    | '/image-generator'
    | '/journal'
    | '/profile'
    | '/teacher'
    | '/video-generator'
    | '/assignments/$id'
    | '/games/$gameId'
    | '/games/map-quiz'
    | '/games/term-match'
    | '/teacher/assignments'
    | '/teacher/classes'
    | '/teacher/quizzes'
    | '/teacher/worksheets'
    | '/games/'
    | '/teacher/gradebook/$assignmentId'
    | '/teacher/quizzes/$id'
    | '/teacher/worksheets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/about'
    | '/assignments'
    | '/chatbot'
    | '/classes'
    | '/dashboard'
    | '/image-generator'
    | '/journal'
    | '/profile'
    | '/teacher'
    | '/video-generator'
    | '/assignments/$id'
    | '/games/$gameId'
    | '/games/map-quiz'
    | '/games/term-match'
    | '/teacher/assignments'
    | '/teacher/classes'
    | '/teacher/quizzes'
    | '/teacher/worksheets'
    | '/games'
    | '/teacher/gradebook/$assignmentId'
    | '/teacher/quizzes/$id'
    | '/teacher/worksheets/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_app/about'
    | '/_app/assignments'
    | '/_app/chatbot'
    | '/_app/classes'
    | '/_app/dashboard'
    | '/_app/image-generator'
    | '/_app/journal'
    | '/_app/profile'
    | '/_app/teacher'
    | '/_app/video-generator'
    | '/_app/assignments/$id'
    | '/_app/games/$gameId'
    | '/_app/games/map-quiz'
    | '/_app/games/term-match'
    | '/_app/teacher/assignments'
    | '/_app/teacher/classes'
    | '/_app/teacher/quizzes'
    | '/_app/teacher/worksheets'
    | '/_app/games/'
    | '/_app/teacher/gradebook/$assignmentId'
    | '/_app/teacher/quizzes/$id'
    | '/_app/teacher/worksheets/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/video-generator': {
      id: '/_app/video-generator'
      path: '/video-generator'
      fullPath: '/video-generator'
      preLoaderRoute: typeof AppVideoGeneratorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teacher': {
      id: '/_app/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AppTeacherRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/image-generator': {
      id: '/_app/image-generator'
      path: '/image-generator'
      fullPath: '/image-generator'
      preLoaderRoute: typeof AppImageGeneratorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/classes': {
      id: '/_app/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chatbot': {
      id: '/_app/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof AppChatbotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assignments': {
      id: '/_app/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/': {
      id: '/_app/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof AppGamesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teacher/worksheets': {
      id: '/_app/teacher/worksheets'
      path: '/worksheets'
      fullPath: '/teacher/worksheets'
      preLoaderRoute: typeof AppTeacherWorksheetsRouteImport
      parentRoute: typeof AppTeacherRoute
    }
    '/_app/teacher/quizzes': {
      id: '/_app/teacher/quizzes'
      path: '/quizzes'
      fullPath: '/teacher/quizzes'
      preLoaderRoute: typeof AppTeacherQuizzesRouteImport
      parentRoute: typeof AppTeacherRoute
    }
    '/_app/teacher/classes': {
      id: '/_app/teacher/classes'
      path: '/classes'
      fullPath: '/teacher/classes'
      preLoaderRoute: typeof AppTeacherClassesRouteImport
      parentRoute: typeof AppTeacherRoute
    }
    '/_app/teacher/assignments': {
      id: '/_app/teacher/assignments'
      path: '/assignments'
      fullPath: '/teacher/assignments'
      preLoaderRoute: typeof AppTeacherAssignmentsRouteImport
      parentRoute: typeof AppTeacherRoute
    }
    '/_app/games/term-match': {
      id: '/_app/games/term-match'
      path: '/games/term-match'
      fullPath: '/games/term-match'
      preLoaderRoute: typeof AppGamesTermMatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/map-quiz': {
      id: '/_app/games/map-quiz'
      path: '/games/map-quiz'
      fullPath: '/games/map-quiz'
      preLoaderRoute: typeof AppGamesMapQuizRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/$gameId': {
      id: '/_app/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof AppGamesGameIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assignments/$id': {
      id: '/_app/assignments/$id'
      path: '/$id'
      fullPath: '/assignments/$id'
      preLoaderRoute: typeof AppAssignmentsIdRouteImport
      parentRoute: typeof AppAssignmentsRoute
    }
    '/_app/teacher/worksheets/$id': {
      id: '/_app/teacher/worksheets/$id'
      path: '/$id'
      fullPath: '/teacher/worksheets/$id'
      preLoaderRoute: typeof AppTeacherWorksheetsIdRouteImport
      parentRoute: typeof AppTeacherWorksheetsRoute
    }
    '/_app/teacher/quizzes/$id': {
      id: '/_app/teacher/quizzes/$id'
      path: '/$id'
      fullPath: '/teacher/quizzes/$id'
      preLoaderRoute: typeof AppTeacherQuizzesIdRouteImport
      parentRoute: typeof AppTeacherQuizzesRoute
    }
    '/_app/teacher/gradebook/$assignmentId': {
      id: '/_app/teacher/gradebook/$assignmentId'
      path: '/gradebook/$assignmentId'
      fullPath: '/teacher/gradebook/$assignmentId'
      preLoaderRoute: typeof AppTeacherGradebookAssignmentIdRouteImport
      parentRoute: typeof AppTeacherRoute
    }
  }
}

interface AppAssignmentsRouteChildren {
  AppAssignmentsIdRoute: typeof AppAssignmentsIdRoute
}

const AppAssignmentsRouteChildren: AppAssignmentsRouteChildren = {
  AppAssignmentsIdRoute: AppAssignmentsIdRoute,
}

const AppAssignmentsRouteWithChildren = AppAssignmentsRoute._addFileChildren(
  AppAssignmentsRouteChildren,
)

interface AppTeacherQuizzesRouteChildren {
  AppTeacherQuizzesIdRoute: typeof AppTeacherQuizzesIdRoute
}

const AppTeacherQuizzesRouteChildren: AppTeacherQuizzesRouteChildren = {
  AppTeacherQuizzesIdRoute: AppTeacherQuizzesIdRoute,
}

const AppTeacherQuizzesRouteWithChildren =
  AppTeacherQuizzesRoute._addFileChildren(AppTeacherQuizzesRouteChildren)

interface AppTeacherWorksheetsRouteChildren {
  AppTeacherWorksheetsIdRoute: typeof AppTeacherWorksheetsIdRoute
}

const AppTeacherWorksheetsRouteChildren: AppTeacherWorksheetsRouteChildren = {
  AppTeacherWorksheetsIdRoute: AppTeacherWorksheetsIdRoute,
}

const AppTeacherWorksheetsRouteWithChildren =
  AppTeacherWorksheetsRoute._addFileChildren(AppTeacherWorksheetsRouteChildren)

interface AppTeacherRouteChildren {
  AppTeacherAssignmentsRoute: typeof AppTeacherAssignmentsRoute
  AppTeacherClassesRoute: typeof AppTeacherClassesRoute
  AppTeacherQuizzesRoute: typeof AppTeacherQuizzesRouteWithChildren
  AppTeacherWorksheetsRoute: typeof AppTeacherWorksheetsRouteWithChildren
  AppTeacherGradebookAssignmentIdRoute: typeof AppTeacherGradebookAssignmentIdRoute
}

const AppTeacherRouteChildren: AppTeacherRouteChildren = {
  AppTeacherAssignmentsRoute: AppTeacherAssignmentsRoute,
  AppTeacherClassesRoute: AppTeacherClassesRoute,
  AppTeacherQuizzesRoute: AppTeacherQuizzesRouteWithChildren,
  AppTeacherWorksheetsRoute: AppTeacherWorksheetsRouteWithChildren,
  AppTeacherGradebookAssignmentIdRoute: AppTeacherGradebookAssignmentIdRoute,
}

const AppTeacherRouteWithChildren = AppTeacherRoute._addFileChildren(
  AppTeacherRouteChildren,
)

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppAssignmentsRoute: typeof AppAssignmentsRouteWithChildren
  AppChatbotRoute: typeof AppChatbotRoute
  AppClassesRoute: typeof AppClassesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppImageGeneratorRoute: typeof AppImageGeneratorRoute
  AppJournalRoute: typeof AppJournalRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTeacherRoute: typeof AppTeacherRouteWithChildren
  AppVideoGeneratorRoute: typeof AppVideoGeneratorRoute
  AppGamesGameIdRoute: typeof AppGamesGameIdRoute
  AppGamesMapQuizRoute: typeof AppGamesMapQuizRoute
  AppGamesTermMatchRoute: typeof AppGamesTermMatchRoute
  AppGamesIndexRoute: typeof AppGamesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppAssignmentsRoute: AppAssignmentsRouteWithChildren,
  AppChatbotRoute: AppChatbotRoute,
  AppClassesRoute: AppClassesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppImageGeneratorRoute: AppImageGeneratorRoute,
  AppJournalRoute: AppJournalRoute,
  AppProfileRoute: AppProfileRoute,
  AppTeacherRoute: AppTeacherRouteWithChildren,
  AppVideoGeneratorRoute: AppVideoGeneratorRoute,
  AppGamesGameIdRoute: AppGamesGameIdRoute,
  AppGamesMapQuizRoute: AppGamesMapQuizRoute,
  AppGamesTermMatchRoute: AppGamesTermMatchRoute,
  AppGamesIndexRoute: AppGamesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
